apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenapp-deployment
  labels:
    app: mavenapp
spec:
  replicas: 2  # This will create 2 Pods (nodes running your container)
  selector:
    matchLabels:
      app: mavenapp
  template:
    metadata:
      labels:
        app: mavenapp
    spec:
      containers:
        - name: mavenapp-container
          image: naval/mavenapp:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenapp-service
spec:
  selector:
    app: mavenapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
